In [1]:
# Librerias a utilizar

import tabula as tb
import pandas as pd
import numpy as np
import PyPDF2
from openpyxl import load_workbook
import os
import glob

In [2]:
#Variable

usuario = os.path.expanduser('~')

In [3]:
def obtener_ultimo_pdf_con_nombre(nombre_buscar, ruta):
    # Crear una lista de todos los archivos PDF que contienen el nombre deseado
    archivos_pdf = glob.glob(os.path.join(ruta, f'*{nombre_buscar}*.pdf'))

    if not archivos_pdf:
        print(f"No se encontraron archivos PDF que contengan '{nombre_buscar}' en el nombre.")
        return None

    # Ordenar la lista por fecha de modificación (el último archivo será el último de la lista)
    archivos_pdf.sort(key=os.path.getmtime, reverse=True)

    # Obtener el último archivo de la lista
    ultimo_pdf = archivos_pdf[0]

    return ultimo_pdf

# Ruta donde se encuentran los archivos PDF
ruta_descargas = f'{usuario}\\Downloads\\'

# Nombre que buscamos en el archivo PDF
nombre_buscar = "METROP"

# Obtener el último archivo PDF con el nombre deseado
ultimo_pdf = obtener_ultimo_pdf_con_nombre(nombre_buscar, ruta_descargas)

if ultimo_pdf:
    print(f"El último archivo PDF con '{nombre_buscar}' en el nombre es: {ultimo_pdf}")
else:
    print("No se encontraron archivos PDF que coincidan con el nombre buscado.")

El último archivo PDF con 'METROP' en el nombre es: C:\Users\56959\Downloads\METROP1260_Metropolitan_Insurance_LLC_23_07_18 17_37_13_37.pdf

In [4]:
#Rutas

file_path = ultimo_pdf
file_out = f'{usuario}\\Desktop\\Proyectos\\FrankWinstonCrum\\Entregables\\'
os.makedirs(file_out, exist_ok=True)

In [5]:
#Lectura de archivo

pdf_reader = tb.read_pdf(file_path, pages="all", multiple_tables=True, stream=False, guess=True, output_format="dataframe")
len(pdf_reader) #visualizar cantidad de tablas recogidas

1

In [6]:
type(pdf_reader) #Visualizar tipo de archivo generado

list

In [7]:
df = pd.concat(pdf_reader) #Convertir la tabla en dataframe
df.head()

,Account\rNumber,Policy Holder,Policy Number,Line of\rBusiness,Carrier,Payment\rDate,Commissionable\rPremium,Commission\rRate,Commission\rAmount,Producer\rFee,Total Paid
0,A207816,Apure Flooring LLC,FGNC0022949102,GL,FWC,06/02/2023,$64.69,15%,$9.70,$0.00,$9.70
1,A219020,ABILIO\rHARDWOOD\rFLOORS LLC,SGNC0023303102,GL,CBS,06/28/2023,$92.08,15%,$13.81,$0.00,$13.81
2,A234564,ANJAZ PAINTING\rLLC,SGNC0024070301,GL,CBS,06/14/2023,$63.03,15%,$9.45,$0.00,$9.45
3,A234564,ANJAZ PAINTING\rLLC,TWNC0000381900,WC,BI,06/14/2023,$170.83,10%,$17.08,$0.00,$17.08
4,A245378,Alex Collazo,SGNC0024487501,GL,CBS,06/02/2023,$159.61,15%,$23.94,$0.00,$23.94

In [8]:

df.drop(df[(df['Account\rNumber'] == 'Agency Totals') | (df['Account\rNumber'] == 'Agency Grand Totals')].index, inplace=True)

#Creación de columnas PH y AN

df['Policy Holder'] = df['Policy Holder'].fillna('') #Los campos en blanco los completa con vacios
df['Policy Holder_2'] = np.where(df['Policy Holder'] == '', df['Account\rNumber'].str[8:], df['Policy Holder']) #DondePH sea igual a blanco, colocame el str desde el valor 8 en adelante, sino colocame el valor original. 
df['Account\rNumber_2'] = np.where(df['Policy Holder'] == '', df['Account\rNumber'].str[:7], df['Account\rNumber']) # ""

df['Policy Number'] = df['Policy Number'].fillna('') #Los campos en blanco los completa con vacios
df['Payment\rDate'] = df['Payment\rDate'].fillna('')
df = df.loc[df['Policy Number'] != ""] #Resulta un DF con todos los varoles diferentes a blanco

df.head()

,Account\rNumber,Policy Holder,Policy Number,Line of\rBusiness,Carrier,Payment\rDate,Commissionable\rPremium,Commission\rRate,Commission\rAmount,Producer\rFee,Total Paid,Policy Holder_2,Account\rNumber_2
0,A207816,Apure Flooring LLC,FGNC0022949102,GL,FWC,06/02/2023,$64.69,15%,$9.70,$0.00,$9.70,Apure Flooring LLC,A207816
1,A219020,ABILIO\rHARDWOOD\rFLOORS LLC,SGNC0023303102,GL,CBS,06/28/2023,$92.08,15%,$13.81,$0.00,$13.81,ABILIO\rHARDWOOD\rFLOORS LLC,A219020
2,A234564,ANJAZ PAINTING\rLLC,SGNC0024070301,GL,CBS,06/14/2023,$63.03,15%,$9.45,$0.00,$9.45,ANJAZ PAINTING\rLLC,A234564
3,A234564,ANJAZ PAINTING\rLLC,TWNC0000381900,WC,BI,06/14/2023,$170.83,10%,$17.08,$0.00,$17.08,ANJAZ PAINTING\rLLC,A234564
4,A245378,Alex Collazo,SGNC0024487501,GL,CBS,06/02/2023,$159.61,15%,$23.94,$0.00,$23.94,Alex Collazo,A245378

In [9]:
#Limpieza de datos:

for column in df.columns:
    df[column] = df[column].str.replace('(', '-', regex=False)
    
def replace_chars_in_df(df, chars_to_replace):
    for column in df.columns:
        for char in chars_to_replace:
            df[column] = df[column].str.replace(char, '', regex=False)

chars_to_replace = ['$',')',',']
replace_chars_in_df(df, chars_to_replace)

In [10]:
#Formateo de columnas:

df = df.rename(columns={'Account\rNumber_2' : 'ACCOUNT NUMBER', 'Policy Holder_2' : 'Insured Name', 'Line of\rBusiness' : 'LINE OF BUSINESS', 'Carrier' : 'CARRIER' , 'Payment\rDate' : 'Policy Eff Date', 'Commissionable\rPremium' : 'Premium', 'Commission\rRate' : 'Comm Percent', 'Commission\rAmount' : 'Comm Amount', 'Producer\rFee' : 'PRODUCER FEE', 'Total Paid' : 'TOTAL PAID'})
df["PRODUCER CODE"] = ''
df["Trans Type Code"] = 'PCH' 
df["VENDOR CODE"] = 'METROP1260'

df = df[['ACCOUNT NUMBER', 'Insured Name', 'Policy Number', 'LINE OF BUSINESS', 'CARRIER', 'Policy Eff Date', 'Premium', 'Comm Percent', 'Comm Amount', 'Trans Type Code', 'PRODUCER FEE', 'TOTAL PAID', 'PRODUCER CODE', 'VENDOR CODE']]

In [11]:
#df.loc[df['ACCOUNT_NUMBER'].str[:7] == 'J205658'] #Verificar info
df.head()

,ACCOUNT NUMBER,Insured Name,Policy Number,LINE OF BUSINESS,CARRIER,Policy Eff Date,Premium,Comm Percent,Comm Amount,Trans Type Code,PRODUCER FEE,TOTAL PAID,PRODUCER CODE,VENDOR CODE
0,A207816,Apure Flooring LLC,FGNC0022949102,GL,FWC,06/02/2023,64.69,15%,9.70,PCH,0.00,9.70,,METROP1260
1,A219020,ABILIO\rHARDWOOD\rFLOORS LLC,SGNC0023303102,GL,CBS,06/28/2023,92.08,15%,13.81,PCH,0.00,13.81,,METROP1260
2,A234564,ANJAZ PAINTING\rLLC,SGNC0024070301,GL,CBS,06/14/2023,63.03,15%,9.45,PCH,0.00,9.45,,METROP1260
3,A234564,ANJAZ PAINTING\rLLC,TWNC0000381900,WC,BI,06/14/2023,170.83,10%,17.08,PCH,0.00,17.08,,METROP1260
4,A245378,Alex Collazo,SGNC0024487501,GL,CBS,06/02/2023,159.61,15%,23.94,PCH,0.00,23.94,,METROP1260

In [12]:
#Formateo de tipo de datos:

df['Premium'] = pd.to_numeric(df['Premium'], errors='coerce')
df['Comm Amount'] = pd.to_numeric(df['Comm Amount'], errors='coerce')
df['PRODUCER FEE'] = pd.to_numeric(df['PRODUCER FEE'], errors='coerce')
df['TOTAL PAID'] = pd.to_numeric(df['TOTAL PAID'], errors='coerce')
df['Policy Eff Date'] = pd.to_datetime(df['Policy Eff Date'], errors='coerce')
df['Policy Eff Date'] = df['Policy Eff Date'].dt.strftime('%m-%d-%Y')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 465 entries, 0 to 516
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ACCOUNT NUMBER    465 non-null    object
 1   Insured Name      465 non-null    object
 2   Policy Number     465 non-null    object
 3   LINE OF BUSINESS  465 non-null    object
 4   CARRIER           465 non-null    object
 5   Policy Eff Date   463 non-null    object
 6   Premium           463 non-null    float64
 7   Comm Percent      465 non-null    object
 8   Comm Amount       463 non-null    float64
 9   Trans Type Code   465 non-null    object
 10  PRODUCER FEE      463 non-null    float64
 11  TOTAL PAID        463 non-null    float64
 12  PRODUCER CODE     465 non-null    object
 13  VENDOR CODE       465 non-null    object
dtypes: float64(4), object(10)
memory usage: 54.5+ KB

In [14]:
# Creamos una lista para almacenar los dataframes
dfs = []

# Creamos una variable para almacenar el índice del inicio de cada nuevo dataframe
start = 0

# Recorremos cada fila en el dataframe
for i in range(len(df)):
    # Si la primera columna contiene 'Account', 'ACCOUNT', o 'account'
    if df.iloc[i, 0] in ['Account', 'ACCOUNT', 'account', 'Account\rNumber']:
        # Agregamos el dataframe actual a la lista
        dfs.append(df.iloc[start:i])
        # Actualizamos el índice de inicio para el próximo dataframe
        start = i

# Agregamos el último dataframe a la lista
dfs.append(df.iloc[start:])

# # Ahora, tenemos una lista de dataframes que podemos escribir en archivos Excel
# for i, df in enumerate(dfs):
#     # Escribimos cada dataframe en un archivo Excel   
#     df.to_excel(f'dataframe{i}.xlsx')

In [15]:
#Copia el resultado de la iteración
df1 = dfs[0].copy()
df2 = dfs[1].copy()
df3 = dfs[2].copy()

#Agregar valor manual
df1.loc[:, 'PRODUCER CODE'] = 'FC126001'
df2.loc[:, 'PRODUCER CODE'] = 'FC126002'
df3.loc[:, 'PRODUCER CODE'] = 'FC126003'

#Limpieza de encabezados adicionales
df2.drop(df2[(df2['CARRIER'] == 'Carrier')].index, inplace=True)
df3.drop(df3[(df3['CARRIER'] == 'Carrier')].index, inplace=True)

In [16]:
df2.head()

,ACCOUNT NUMBER,Insured Name,Policy Number,LINE OF BUSINESS,CARRIER,Policy Eff Date,Premium,Comm Percent,Comm Amount,Trans Type Code,PRODUCER FEE,TOTAL PAID,PRODUCER CODE,VENDOR CODE
325,A221558,ACM HOME\rIMPROVEMENT\rLLC,FGFL0023865801,GL,FWC,06-08-2023,313.65,15%,47.05,PCH,0.0,47.05,FC126002,METROP1260
326,A293146,AP GROUP\rINTERNATIONAL\rINC,FGFL0026200800,GL,FWC,06-02-2023,650.92,15%,97.64,PCH,0.0,97.64,FC126002,METROP1260
327,A303724,AKEMI CARPET\rSERVICES LLC,BGFL0026652500,GL,CB,06-28-2023,59.97,15%,9.00,PCH,0.0,9.00,FC126002,METROP1260
328,A321694,Camilo Vidal and\rChad Ritcher,FWNC0027387100,WC,FWC,06-04-2023,754.04,10%,75.40,PCH,0.0,75.40,FC126002,METROP1260
329,A332203,Ardon Flooring\rServices LLC,SGNC0027776700,GL,CBS,06-20-2023,59.59,15%,8.94,PCH,0.0,8.94,FC126002,METROP1260

In [17]:
#Lectura de texto fecha de reporte

archivo = open(file_path, 'rb')
pdf_reader = PyPDF2.PdfReader(archivo)
page = pdf_reader.pages[0]
text = page.extract_text()
fArchivo = text.split('\n')
fArchivo = fArchivo[1]

In [18]:
fArchivo

'Jun 2023'

In [19]:
#Exportar archivos excel

df1.to_excel(f'{file_out}FrankWinstonCrum-METROP126001-Statement-{fArchivo}.xlsx', sheet_name='Sheet1', index=False)
df2.to_excel(f'{file_out}FrankWinstonCrum-METROP126002-Statement-{fArchivo}.xlsx', sheet_name='Sheet1', index=False)
df3.to_excel(f'{file_out}FrankWinstonCrum-METROP126003-Statement-{fArchivo}.xlsx', sheet_name='Sheet1', index=False)

In [20]:
#Auto ajustar columnas

Excel126001 = f'{file_out}FrankWinstoncrum-METROP126001-Statement-{fArchivo}.xlsx'
wb = load_workbook(Excel126001)
worksheet = wb['Sheet1']

for i, col in enumerate(df1.columns):
    column_width = max(df1[col].astype(str).map(len).max(), len(col)) + 2
    worksheet.column_dimensions[worksheet.cell(row=1, column=i + 1).column_letter].width = column_width

wb.save(Excel126001)

Excel126002 = f'{file_out}FrankWinstoncrum-METROP126002-Statement-{fArchivo}.xlsx'
wb = load_workbook(Excel126002)
worksheet = wb['Sheet1']

for i, col in enumerate(df1.columns):
    column_width = max(df1[col].astype(str).map(len).max(), len(col)) + 2
    worksheet.column_dimensions[worksheet.cell(row=1, column=i + 1).column_letter].width = column_width

wb.save(Excel126002)

Excel126003 = f'{file_out}FrankWinstoncrum-METROP126003-Statement-{fArchivo}.xlsx'
wb = load_workbook(Excel126003)
worksheet = wb['Sheet1']

for i, col in enumerate(df1.columns):
    column_width = max(df1[col].astype(str).map(len).max(), len(col)) + 2
    worksheet.column_dimensions[worksheet.cell(row=1, column=i + 1).column_letter].width = column_width

wb.save(Excel126003)

In [21]:
print("Script finalizado")

Script finalizado